name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Deploy no gitHub pages
        uses: peaceiris/actions-gh-page@v3
        with:
          github_token{{ secrets.GITHUB_TOKEN}}
          Publish_dir: ./

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest
